[package]
name = "uuid_macros"
version = "0.1.0"
authors = ["Artur Kowalski <arturkow2000@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
uuid = "0.8.1"
quote = "1.0"
syn = "1.0"